List<Map<String, dynamic>> blinkitProducts = [
  {
    'id': '1',
    'name': 'Fresh Apple',
    'price': 30,
    'category': 'Fruits & Veggies',
    'image': 'assets/products/apple.png',
    'description': 'Fresh, juicy apples directly sourced from farms.',
  },
  {
    'id': '2',
    'name': 'Tomato',
    'price': 40,
    'category': 'Fruits & Veggies',
    'image': 'assets/products/tomato.png',
    'description': 'Fresh red tomatoes perfect for daily cooking.',
  },
  {
    'id': '3',
    'name': 'Banana',
    'price': 60,
    'category': 'Fruits & Veggies',
    'image': 'assets/products/banana.png',
    'description': 'Healthy and naturally sweet bananas.',
  },
  {
    'id': '4',
    'name': 'Potato Chips',
    'price': 30,
    'category': 'Snacks',
    'image': 'assets/products/chips.png',
    'description': 'Crispy and tasty potato chips.',
  },
  {
    'id': '5',
    'name': 'Cream Biscuit',
    'price': 25,
    'category': 'Snacks',
    'image': 'assets/products/biscuit.png',
    'description': 'Crunchy biscuits with creamy filling.',
  },
  {
    'id': '6',
    'name': 'Mango Pickle',
    'price': 90,
    'category': 'Pickles',
    'image': 'assets/products/pickle.png',
    'description': 'Traditional spicy mango pickle.',
  },
  {
    'id': '7',
    'name': 'Fruit Juice',
    'price': 110,
    'category': 'Beverages',
    'image': 'assets/products/Fruit Juice.png',
    'description': 'Refreshing mixed fruit juice made from fresh fruits.',
  },
  {
    'id': '8',
    'name': 'Cold Drink',
    'price': 45,
    'category': 'Beverages',
    'image': 'assets/products/cold_drink.png',
    'description': 'Chilled soft drink to refresh you.',
  },
  {
    'id': '9',
    'name': 'Basmati Rice',
    'price': 220,
    'category': 'Grocery',
    'image': 'assets/products/rice.png',
    'description': 'Premium long-grain basmati rice.',
  },
  {
    'id': '10',
    'name': 'Wheat Flour',
    'price': 180,
    'category': 'Grocery',
    'image': 'assets/products/flour.png',
    'description': 'Freshly milled wheat flour.',
  },
  {
    'id': '11',
    'name': 'Milk Bread',
    'price': 35,
    'category': 'Bakery',
    'image': 'assets/products/bread.png',
    'description': 'Soft and fresh milk bread.',
  },
  {
    'id': '12',
    'name': 'Chocolate Cake',
    'price': 150,
    'category': 'Bakery',
    'image': 'assets/products/cake.png',
    'description': 'Delicious chocolate cake for sweet cravings.',
  },
  {
    'id': '13',
    'name': 'Instant Noodles',
    'price': 14,
    'category': 'Instant Food',
    'image': 'assets/products/instant_noodles.png',
    'description': 'Quick and tasty instant noodles, ready in minutes.',
  },
  {
    'id': '14',
    'name': 'Soup Mix',
    'price': 35,
    'category': 'Instant Food',
    'image': 'assets/products/soup.png',
    'description': 'Instant soup mix for quick and easy meals.',
  },
];
