// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured for this Firebase project.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'This platform is not configured for Firebase.',
        );
    }
  }

  /// ✅ ANDROID — GrocDrop
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcTaYQzkQJs2ISQtSzPj4YzZiKe7NsJA',
    appId: '1:665130055650:android:c164407ed89b1b4f82abbb',
    messagingSenderId: '665130055650',
    projectId: 'grocdrop',
    storageBucket: 'grocdrop.firebasestorage.app',
  );
}
